on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    name: Build with Vue and deploy to gh page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          persist-credentials: false

      - name: Install and Build
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm install
          npm run build
          cd dist
          cp index.html 404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
